name: Test Coverage

on:
  pull_request:
    branches: [ main, develop, test, feature/** ]

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest pytest-json-report==1.5.0 coverage requests

      - name: Run Tests with JSON and Coverage
        continue-on-error: true
        run: |
          set +e
          coverage run --source=app -m pytest \
            --json-report \
            --json-report-file=pytest-report.json \
            tests

          TEST_EXIT_CODE=$?

          coverage xml -o coverage.xml || true
          set -e
          exit $TEST_EXIT_CODE

      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload Pytest JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.json



